---
title: "Astronaut database"
output: github_document
---
## TidyTuesday [2020-07-14]
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE, 
  fig.width = 9,
  fig.height = 6,
  out.width="100%"
  )
```

```{r, warning=FALSE, message=FALSE}
library(tidytuesdayR)
library(tidyverse)
```

A quick look at the data set
```{r}
d <- tidytuesdayR::tt_load("2020-07-14")[[1]]
```

```{r}
glimpse(d)
```

First thought, what is the difference in time between when an astronaut is first selected and when they go on their first mission? How does it vary by nationality?
```{r}
d %>% 
  filter(mission_number == 1) %>% # first mission
  mutate(age_at_selection = year_of_selection - year_of_birth,
         age_at_first_mission = year_of_mission - year_of_birth,
         diff = age_at_first_mission - age_at_selection) %>% 
  group_by(nationality) %>% 
  filter(n() > 20) %>% # Select high count nationalities
  gather(k, v, age_at_selection, age_at_first_mission, diff) %>% 
  mutate(k_pretty = case_when(k == "age_at_selection" ~ "Age at selection year",
                              k == "age_at_first_mission" ~ "Age at first mission",
                              k == "diff" ~ "Difference",
                              TRUE ~ "Error")) %>% 
  ggplot()+
  geom_histogram(aes(v, ..density.., fill=k_pretty), 
                 position = "identity", 
                 alpha=1/2, binwidth = 1, center=0)+
  facet_wrap(~nationality, scales = "free_y", ncol=1)+
  scale_fill_viridis_d("")+
  scale_x_continuous(breaks=scales::pretty_breaks(10))+
  theme(legend.position = "bottom")+
  labs(title = "First mission - distribution of age at selection-year and age at mission-year",
       subtitle = "Facetted by the two biggest astronaut nationalities",
       x = "Age [years]",
       y = "Density estimate")
```



```{r, fig.width=8, fig.height=8}
pd <-
  d %>% 
  group_by(year_of_mission) %>% 
  summarise(year_hours = sum(hours_mission)) %>% 
  mutate(text_label = case_when(year_hours == max(year_hours) ~ 
                                  glue::glue("{round(year_hours)} astronaut mission hours [{year_of_mission}]"),
                                TRUE ~ NA_character_))


pd %>% 
  ggplot(aes(year_of_mission, year_hours))+
  geom_col(aes(fill=year_hours))+
  coord_polar(start=0)+
  scale_fill_viridis_c(option="viridis", begin = 0.1)+
  expand_limits(y = -50000)+
  geom_text(aes(label = text_label), hjust="outward", col="grey80", nudge_y=8000, size=3)+
  annotate(geom="segment", x=1960, xend=1960, y=0, yend=max(pd$year_hours)*1.1, col="grey80", size=0.1)+
  annotate(geom="text", x=1960, y=max(pd$year_hours)*1.2, label="Year\n[2019 - 1960]", size=3, colour="grey80")+
  annotate(geom="text", x=1960+((2019-1960)/2), y=max(pd$year_hours), label="Total astronaut mission hours by year\n#tidytuesday", size=3, colour="grey60")+
  # geom_segment(aes(x=1963, xend=2017, y=max(pd$year_hours)*1.2, yend=max(pd$year_hours)*1.2), col="white")+
  
  theme_void()+
  theme(panel.background = element_rect(fill="grey10"),
        plot.background = element_rect(fill="grey10"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "",
        axis.text.x = element_blank(),
        axis.line.y = element_blank(),
        plot.title = element_text(colour="white", hjust = 0.5),
        plot.subtitle = element_text(colour="white", hjust = 0.5),
        plot.caption = element_text(colour="white", hjust = 0.5))
  
ggsave("astro-hours-viridis.pdf", width=9, height=9)
ggsave("astro-hours-viridis.png", width=9, height=9)
```

```{r, fig.width=8, fig.height=8}
last_plot() + scale_fill_viridis_c(option="plasma")
ggsave("astro-hours-plasma.pdf", width=9, height=9)  
```

